--
-- PostgreSQL database cluster dump
--

\restrict ju35oKYpuyGzwGETP6RxvQe29X4CA0fM4LC0QueQLpbh0lbrC1ylwX8G83ZVuzg

SET default_transaction_read_only = off;

SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

--
-- Roles
--

CREATE ROLE konno;
ALTER ROLE konno WITH SUPERUSER INHERIT CREATEROLE CREATEDB LOGIN REPLICATION BYPASSRLS PASSWORD 'SCRAM-SHA-256$4096:3xTosoQ2BiPvfAK0DV0cbQ==$6xpkw305BwOYnMD3q00Zhz07XofC5b+e6L3aNlY9usk=:Hn3sY96GACGlESHRLPWzWFGhj3ft/hpZHzgZLAyP6lc=';






\unrestrict ju35oKYpuyGzwGETP6RxvQe29X4CA0fM4LC0QueQLpbh0lbrC1ylwX8G83ZVuzg

--
-- Databases
--

--
-- Database "template1" dump
--

\connect template1

--
-- PostgreSQL database dump
--

\restrict cV7gZlNxRI7clPD3r6VbrTcpIXBk6PF9fvPhTtLvpJJ4C2JFgPfIcCl0vaVdLKZ

-- Dumped from database version 14.20 (Debian 14.20-1.pgdg13+1)
-- Dumped by pg_dump version 14.20 (Debian 14.20-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

\unrestrict cV7gZlNxRI7clPD3r6VbrTcpIXBk6PF9fvPhTtLvpJJ4C2JFgPfIcCl0vaVdLKZ

--
-- Database "postgres" dump
--

\connect postgres

--
-- PostgreSQL database dump
--

\restrict LHA9yPoeQdoqVYMnVFOF8JRbUIQuUiyJELcpapDzfmsGwy28zaRsqmyohNqUEpO

-- Dumped from database version 14.20 (Debian 14.20-1.pgdg13+1)
-- Dumped by pg_dump version 14.20 (Debian 14.20-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- PostgreSQL database dump complete
--

\unrestrict LHA9yPoeQdoqVYMnVFOF8JRbUIQuUiyJELcpapDzfmsGwy28zaRsqmyohNqUEpO

--
-- Database "receipt_db" dump
--

--
-- PostgreSQL database dump
--

\restrict PGyhjz8Kz5ObgT8DGHsgFeH0tyZ16jZBmEHLYUFAXRZ1RrZcHJH9Sni4lc12vlq

-- Dumped from database version 14.20 (Debian 14.20-1.pgdg13+1)
-- Dumped by pg_dump version 14.20 (Debian 14.20-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: receipt_db; Type: DATABASE; Schema: -; Owner: konno
--

CREATE DATABASE receipt_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE receipt_db OWNER TO konno;

\unrestrict PGyhjz8Kz5ObgT8DGHsgFeH0tyZ16jZBmEHLYUFAXRZ1RrZcHJH9Sni4lc12vlq
\connect receipt_db
\restrict PGyhjz8Kz5ObgT8DGHsgFeH0tyZ16jZBmEHLYUFAXRZ1RrZcHJH9Sni4lc12vlq

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account_emailaddress; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.account_emailaddress (
    id integer NOT NULL,
    email character varying(254) NOT NULL,
    verified boolean NOT NULL,
    "primary" boolean NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.account_emailaddress OWNER TO konno;

--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.account_emailaddress ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailaddress_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account_emailconfirmation; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.account_emailconfirmation (
    id integer NOT NULL,
    created timestamp with time zone NOT NULL,
    sent timestamp with time zone,
    key character varying(64) NOT NULL,
    email_address_id integer NOT NULL
);


ALTER TABLE public.account_emailconfirmation OWNER TO konno;

--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.account_emailconfirmation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_emailconfirmation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO konno;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO konno;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO konno;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO konno;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO konno;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO konno;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO konno;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO konno;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO konno;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO konno;

--
-- Name: receipts_pdf番号; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public."receipts_pdf番号" (
    id bigint NOT NULL,
    "PDF_num" character varying(50) NOT NULL,
    upload character varying(100) NOT NULL,
    processed boolean NOT NULL
);


ALTER TABLE public."receipts_pdf番号" OWNER TO konno;

--
-- Name: receipts_pdf番号_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public."receipts_pdf番号" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."receipts_pdf番号_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receipts_receipt; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public.receipts_receipt (
    id bigint NOT NULL,
    "日付" date NOT NULL,
    "価格" integer NOT NULL,
    "登録番号" bigint NOT NULL,
    "備考" character varying(255),
    "項目コード_id" character varying(32) NOT NULL,
    "PDF番号_id" bigint NOT NULL,
    CONSTRAINT "receipts_receipt_価格_check" CHECK (("価格" >= 0))
);


ALTER TABLE public.receipts_receipt OWNER TO konno;

--
-- Name: receipts_receipt_id_seq; Type: SEQUENCE; Schema: public; Owner: konno
--

ALTER TABLE public.receipts_receipt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.receipts_receipt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: receipts_項目リスト; Type: TABLE; Schema: public; Owner: konno
--

CREATE TABLE public."receipts_項目リスト" (
    "項目コード" character varying(32) NOT NULL,
    "項目印字名" character varying(100) NOT NULL,
    "項目短縮名" character varying(50) NOT NULL,
    "項目レポート分類区分" character varying(100) NOT NULL
);


ALTER TABLE public."receipts_項目リスト" OWNER TO konno;

--
-- Data for Name: account_emailaddress; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.account_emailaddress (id, email, verified, "primary", user_id) FROM stdin;
\.


--
-- Data for Name: account_emailconfirmation; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.account_emailconfirmation (id, created, sent, key, email_address_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add email address	7	add_emailaddress
26	Can change email address	7	change_emailaddress
27	Can delete email address	7	delete_emailaddress
28	Can view email address	7	view_emailaddress
29	Can add email confirmation	8	add_emailconfirmation
30	Can change email confirmation	8	change_emailconfirmation
31	Can delete email confirmation	8	delete_emailconfirmation
32	Can view email confirmation	8	view_emailconfirmation
33	Can add 項目リスト	9	add_項目リスト
34	Can change 項目リスト	9	change_項目リスト
35	Can delete 項目リスト	9	delete_項目リスト
36	Can view 項目リスト	9	view_項目リスト
41	Can add receipt	11	add_receipt
42	Can change receipt	11	change_receipt
43	Can delete receipt	11	delete_receipt
44	Can view receipt	11	view_receipt
37	Can add pd f番号	10	add_pdf番号
38	Can change pd f番号	10	change_pdf番号
39	Can delete pd f番号	10	delete_pdf番号
40	Can view pd f番号	10	view_pdf番号
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$870000$1lZr2KnNlQvBE9MjPseqic$Vzo3Bd8hFREu1ekPalwwO10xEXyzDHEVBV0JeQjB5+w=	2025-12-22 05:16:59.687445+00	t	konno			kkonno@soliton-cm.com	t	t	2024-09-17 08:06:18.394+00
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2025-12-22 05:29:29.211721+00	169	169	2	[{"changed": {"fields": ["Processed"]}}]	10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	account	emailaddress
8	account	emailconfirmation
9	receipts	項目リスト
11	receipts	receipt
10	receipts	pdf番号
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2025-09-27 00:57:40.960084+00
2	auth	0001_initial	2025-09-27 00:57:41.040967+00
3	account	0001_initial	2025-09-27 00:57:41.077288+00
4	account	0002_email_max_length	2025-09-27 00:57:41.082858+00
5	account	0003_alter_emailaddress_create_unique_verified_email	2025-09-27 00:57:41.098071+00
6	account	0004_alter_emailaddress_drop_unique_email	2025-09-27 00:57:41.105542+00
7	account	0005_emailaddress_idx_upper_email	2025-09-27 00:57:41.113887+00
8	account	0006_emailaddress_lower	2025-09-27 00:57:41.119888+00
9	account	0007_emailaddress_idx_email	2025-09-27 00:57:41.134186+00
10	account	0008_emailaddress_unique_primary_email_fixup	2025-09-27 00:57:41.140465+00
11	account	0009_emailaddress_unique_primary_email	2025-09-27 00:57:41.148707+00
12	admin	0001_initial	2025-09-27 00:57:41.171919+00
13	admin	0002_logentry_remove_auto_add	2025-09-27 00:57:41.177309+00
14	admin	0003_logentry_add_action_flag_choices	2025-09-27 00:57:41.184438+00
15	contenttypes	0002_remove_content_type_name	2025-09-27 00:57:41.193749+00
16	auth	0002_alter_permission_name_max_length	2025-09-27 00:57:41.19928+00
17	auth	0003_alter_user_email_max_length	2025-09-27 00:57:41.204601+00
18	auth	0004_alter_user_username_opts	2025-09-27 00:57:41.210337+00
19	auth	0005_alter_user_last_login_null	2025-09-27 00:57:41.21544+00
20	auth	0006_require_contenttypes_0002	2025-09-27 00:57:41.217295+00
21	auth	0007_alter_validators_add_error_messages	2025-09-27 00:57:41.222577+00
22	auth	0008_alter_user_username_max_length	2025-09-27 00:57:41.231718+00
23	auth	0009_alter_user_last_name_max_length	2025-09-27 00:57:41.236919+00
24	auth	0010_alter_group_name_max_length	2025-09-27 00:57:41.24295+00
25	auth	0011_update_proxy_permissions	2025-09-27 00:57:41.248435+00
26	auth	0012_alter_user_first_name_max_length	2025-09-27 00:57:41.254792+00
27	receipts	0001_initial	2025-09-27 00:57:41.276743+00
28	receipts	0002_receipt_pdf番号	2025-09-27 00:57:41.282952+00
29	receipts	0003_pdf番号_alter_receipt_pdf番号	2025-09-27 00:57:41.306253+00
30	receipts	0004_pdf番号_upload	2025-09-27 00:57:41.309474+00
31	receipts	0005_rename_pdf番号_pdf番号_pdf_num_alter_pdf番号_upload	2025-09-27 00:57:41.312535+00
32	receipts	0006_pdf番号_processed_alter_pdf番号_upload	2025-09-27 00:57:41.315927+00
33	receipts	0007_alter_receipt_pdf番号	2025-09-27 00:57:41.333914+00
34	receipts	0008_alter_receipt_価格_alter_receipt_登録番号	2025-09-27 00:57:41.338504+00
35	sessions	0001_initial	2025-09-27 00:57:41.355657+00
36	receipts	0009_alter_receipt_登録番号	2025-09-27 01:14:41.541125+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
js1y9w05feb2prw9ks5dbqok795kx5oc	.eJxVj7tuwzAMAP-Fs2FQqvXy2L1fUBQGJdG1m0YKLBlNEOTfG7VZshG84wG8AoWQ91Qn2uvCqa6B6prTdOS65FhgfL_C_wwjnKiUn7xF6IAqjMIo66S1BnsltFSoO9gLb4mOfLcPOaUMt48O_uJTQ9PaOgKedp7CgVMD8YvSZ-5DTnVbfd-U_kFL_5Yjf78-3KfAQmW5X7OfpXRahcEZwxpRCXYsBgyOnBhmEa3x3rBHI8UcNAZPOFv0ikTAF9-ihUtp__P5tG4XGPH2C1TqYFo:1v2HkU:TS8SuBgKTyqAyDAwe41LtfaBZfbVyVvQVPyyU4HKNn8	2025-10-10 23:21:10.54+00
ccnsdko37mcvmwt5svw5vyxd4694c6ss	.eJxVj8FuwyAMQP_F5ygyWQghx933BdMUGeMsrCtUgWitqv77ytZLb5bf85N8BWJOeywz7WWVWAJTCSnORylr8hmm9yv8zzDBiXL-SZuHBqjApIy22FtrdYtmHNGaBvYsW6Sj3O1DijHB7aOBv_hc0RxqR8HTzhEfJFbgvyh-ppZTLFtwbVXaB83tW_Ly_fpwnwIr5fV-LW7pOjto7q0xMiBqJVZUj2zJqn5RfjTOGXFoOrXwgOwIlxGdJsX44mo0S871fzmfwnaBCW-_Yyhgaw:1v2nG7:T4TGdtPG-ZVrDX2NCsYdnwhm3lhWWHjOzB_KtTN234o	2025-10-12 08:59:55.097077+00
zv4bqnna2urqt3cconz1sqz4rjsbec7v	.eJxVj8FuwyAMQP_F5wgBgRBy3L1fME2RAWdhXaEKRO1U9d9Xtl56s_yen-QboPd5T3XGva6UavRYY07zieqaQ4Hp_Qb_M0xwxlIueQvQAVaYhNFWKzFIw-TIbd-rDvZCW8ITPexjTinD_aODv_jc0BxbR8DLzqE_UmogfGH6zMznVLfoWFPYkxZ2yIG-357uS2DFsj6uyS1S2kF7ZY2hgXMtyJJQ3Fu0Qi0ijMY5Q44bKRY_cO-QLyN3GoXnvWvRQqW0_-l6jtsPTPz-C1E_YFY:1v4r9f:akDaxSGwYkiDpvqufjQhpPio-3sNMdcHQo9HEVHaDT8	2025-10-18 01:33:47.29732+00
wj401mv61fzohsyt11u3su1ymct5i3s2	.eJxVj8FOwzAMQP_F5yqKS9osPXLnCxCqHMelYSyZmlSApv07C-yym-X3_CRfgJjznupMe10l1chUY07zSeqaQ4Hp9QL_M0xwplK-8hagA6owoR2cM6MbUSH2zhjTwV5kS3SSm33MKWW4vnXwF58bmmPrIDzsPPFRUgPhg9J7VpxT3aJXTVF3WtRLDvL5fHcfAiuV9XYtful7Nw5snLUyaj2gOEGj2ZFDs2A4WO-teG17XHjU7EkvB-0HQtZPvkWLlNL-l-9z3H5g0tdfVpxgXA:1v6YbJ:5cf4g-LzoEdtg46eXZPpkNb9nyXJ_SJhUI781Mzz2rc	2025-10-22 18:09:21.129825+00
ozwm2zjqp6ekwo61m739m0karktt60fh	.eJxVj8FuwyAMht_F5wjhJISQ4-59gmmKDDgL6wpVINqmqu--sPXSm-Xv9yf_NyDn0h7LTHtZOZbgqIQU5wuXNfkM0-sN_meY4Eo5f6XNQwNUYEI9oJRKYSd0h72SYwN75i3ShY_0OcWY4P7WwJ98rmgO1YPwtLPkzhwr8B8U35NwKZYtWFEj4kGzOCXPny-P7JNgpbwe12yXtjWDcr3RmofjNWTD2EtnyGC_oB-1tZqt1C0ubpDOklxGaRWhk52t0sw51_78fQ3bD0zy_gtAkmBD:1vAzyj:RlUwXkiSEANEbQujGcuY6y9BX2gmrIRznCJCQYPX4vw	2025-11-04 00:11:53.750133+00
3g8gy5o7k6mms1hm7mmttgtl7wwm36v9	.eJxVj8tuwyAQAP9lzxYCal4-9t4vqCprgXVN00BksJooyr83tLnkttqZHWmvgCGUPbcZ97ZSbilgSyXPR2priRWm9yv8zzDBCWv9KVuEAbDBJIyWUllhRya1tFYNsFfaMh7pLh9KzgVuHwP8teeO5tQzAp52HsOBcgfxC_NnYaHktiXPusIetLK3Eun79eE-BVas6_2a_CKl0yqMzhjSnCtBjsTIg0MnxkVEa7w35LmRYgmaB498sdwrFIG_-B6tVGt_n86ntF1g4rdfDk9gJQ:1vGFr6:RLDZoh9kPRWKt3hNHAwZWAQeIhvIIYkPXI7z-jgbyzs	2025-11-18 12:09:44.280034+00
q7eydryr990l1hmybxqcv8d4dcwtchg9	.eJxVj8tuwyAQRf9l1hYC_CB42X2-oKqsYRjXNA1EBiupovx7TZtNdjNzzxzp3gGJ0hbLhFtZOJZAWEKK05nLknyG8f0O_zOMcMGcr2n10AAWGJUZdKtapVthWm32rYEt8xrxzDt9SjEmeHw08CefajSF6lHwcnNIJ4418F8YP5OgFMsanKiIeKZZHJPn77cn-yJYMC_7N7tZazv01FljeJCyV2xZdZIsWtXNyh-Mc4adNFrNNEhyKOeDdD0qkq2r0sw51_58u4T1B0b5-AVFs2BJ:1vGU9D:NlTaZyTWp25dqb6VyB3ATvdzSKM3ihgWBvwrDpJjPeY	2025-11-19 03:25:23.75019+00
sw5c0rtvdhke4orzmdud7awr4enmzi72	.eJxVj8FuwyAMQP_F5wiZNATIcfd-wTRFBpyFdYUqEG1T1X9f2XrpzfJ7fpKvQN7nPdWZ9rpyqtFTjTnNZ65rDgWm1yv8zzDBhUr5yluADqjCJPV4QG1Mr4RUCs3QwV54S3Tmu3zKKWW4vXXw154bmmPLSHjaOfInTg2ED0rvWfic6hadaIp40CKOOfDny8N9CqxU1vs1u6Xv7aj8YLXmEVFJtiwH9JasHBYZjHZOs0Pdy8WP6B3hYtApkh4PrkULl9Le5-9L3H5gwtsvCjdgIA:1vJhLF:Hseg_Odo94oubg979MZ0fX7VLwyZHOOD5_6siGosXYs	2025-11-28 00:07:05.172604+00
92yq56xhecs11d08upo8p4id6tnr13ji	.eJxVj8FuwyAMQP_F5yjCJISQ4-79gmmKDDgL6wpVIGqnqv--svXSm-X3_CTfgJxLeywz7WXlWIKjElKcT1zW5DNM7zf4n2GCM-V8SZuHBqjAhHroUHRayhZRohpVA3vmLdKJH_YxxZjg_tHAX3yuaA61g_Cys-SOHCvwXxQ_U-tSLFuwbVXaJ83tIXn-fnu6L4GV8vq4ZrtIaQbleqM1D0IoZMPYC2fIYL-gH7W1mq3QEhc3CGdJLKOwitCJztZo5pzr_3w9h-0HJnH_BT7lYEE:1vJnoo:ZdHHm9KmXlPmlYNhhme_oSwvSyEVRnTC-4VsgDFw4E4	2025-11-28 07:02:02.140985+00
cxhiekbimupl5xexlvnggb9kvmco2ict	.eJxVj8FuwyAMQP_F5yiChEDIcfd-wTRFxjgL6wpVIGqnqv--svXSm-X3_CTfAInSHsuMe1k5lkBYQorzicuafIbp_Qb_M0xwxpwvafPQABaYpNG9Ukb1ujVaq2FsYM-8RTzxQz6mGBPcPxr4a88VzaFmJLzsHNKRYwX-C-NnainFsgXXVqV90twekufvt6f7Elgxr49rdkvXWT2QssawFmKQbFkqQRatVIv0o3HOsBOmkwtpQQ7FMgo3oCTRuxrNnHN9n6_nsP3AJO6_E3hgKw:1vLFEa:ws_jc9RiXxUlEopkO6T2zSt_Z-nK2eQdgr5RJHaFLQU	2025-12-02 06:30:36.775125+00
p1wvzrr0spqvwils5ryw3aaq0xec754n	.eJxVj8FuwyAMQP_F5wjhlEDIcfd-wTRFBpyFdYUqEG1T1X9f2XrpzfJ7fpKvQN7nPdWZ9rpyqtFTjTnNZ65rDgWm1yv8zzDBhUr5yluADqjChEYfrEG0gxitkVqpDvbCW6Iz3-1TTinD7a2Dv_jc0BxbB-Fp58ifODUQPii9Z-Fzqlt0oiniQYs45sCfLw_3KbBSWe_X7Ja-t3rwyhrDWsoB2TIq6S1ZVAuG0Thn2EnT4-K19I7kMko3EHp5cC1auJT2P39f4vYDk7z9AlqnYGE:1vNRUJ:muerlRm4-Jw-V7LkLEbvBoprqn-UJq4atso0jNlYNwA	2025-12-08 07:59:55.934072+00
mbv3pbvlduwzmg8umym29oarttsxhhny	.eJxVj0luwzAMRe_CtWFQHjR42X1OUBQGJdG1mkYKLBltEeTutdpssiP4Ph_4b0DOpT2WmfaycizBUQkpzhcua_IZptcb_M8wwZVy_kqbhwaowCSUHFF12JtWatHrXjewZ94iXfhIn1OMCe5vDfzJ54rmUD0CnnaW3JljBf6D4ntqXYplC7atkfZBc3tKnj9fHtknwUp5Pa7ZLl1n5OgGoxRLxFGwYTGgM2TEsAivlbWK7fG0WJxEZwkXjXYk4bC3VZo559qfv69h-4EJ779RymBX:1vS3rr:JMaOQ9GJ5ybbRzk8CgMx40uHemlJIHQi2HeQ7WOif14	2025-12-21 01:47:19.697567+00
bht9gqg7kula4exv8mcudcwsz43zk9qv	.eJxVj8FuwyAMQP_F5whBGqDkuHu_YJoiY5yFdYUqELVT1X9f2XrpzfJ7fpJvgER5S3XCrS6caiSsMafpxHXJocD4foP_GUY4YymXvAboACuMyhrtjJJ6J7TT2hjdwVZ4TXjih33MKWW4f3TwF58ammLrKHjZeaQjpwbCF6bPLCinukYvmiKetIhDDvz99nRfAguW5XHNfu57ZzQNzlo2UmrFjtUgyaFTw6zC3npv2Uvbq5mMJI9y3kuvUZHc-RYtXEr7n6_nuP7AKO-_V_FgXg:1vVn8n:zPuPJmhnYz1xBNwaGmBs3OLgpSq8WFdQvNPYjZilDK4	2025-12-31 08:44:13.604499+00
\.


--
-- Data for Name: receipts_pdf番号; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public."receipts_pdf番号" (id, "PDF_num", upload, processed) FROM stdin;
1	IMG_3187.JPG	upload_images/IMG_3187_nXD3QlI.JPG	t
2	IMG_3188.JPG	upload_images/IMG_3188_0k54BYH.JPG	t
3	IMG_3189.JPG	upload_images/IMG_3189.JPG	t
4	IMG_3190.JPG	upload_images/IMG_3190.JPG	t
5	IMG_3191.JPG	upload_images/IMG_3191.JPG	t
6	IMG_3192.JPG	upload_images/IMG_3192.JPG	t
7	IMG_3193.JPG	upload_images/IMG_3193.JPG	t
9	IMG_3196.JPG	upload_images/IMG_3196.JPG	t
10	IMG_3202.JPG	upload_images/IMG_3202.JPG	t
11	20240925_102644_Page 1	upload_images/20240925_102644_page_1.jpg	t
12	IMG_3213.JPG	upload_images/IMG_3213.JPG	t
13	IMG_3214.JPG	upload_images/IMG_3214.JPG	t
14	IMG_3217.JPG	upload_images/IMG_3217.JPG	t
15	IMG_3281.JPG	upload_images/IMG_3281.JPG	t
16	IMG_3282.JPG	upload_images/IMG_3282.JPG	t
17	IMG_3283.JPG	upload_images/IMG_3283.JPG	t
18	IMG_3288.JPG	upload_images/IMG_3288.JPG	t
19	IMG_3291.JPG	upload_images/IMG_3291.JPG	t
20	IMG_3311.JPG	upload_images/IMG_3311.JPG	t
21	IMG_3312.JPG	upload_images/IMG_3312.JPG	t
22	IMG_3313.JPG	upload_images/IMG_3313.JPG	t
23	IMG_3525.JPG	upload_images/IMG_3525.JPG	t
24	IMG_3526.JPG	upload_images/IMG_3526.JPG	t
25	IMG_3530.JPG	upload_images/IMG_3530.JPG	t
26	IMG_3531.JPG	upload_images/IMG_3531.JPG	t
27	IMG_3534.JPG	upload_images/IMG_3534.JPG	t
28	IMG_3533.JPG	upload_images/IMG_3533.JPG	t
29	IMG_3535.JPG	upload_images/IMG_3535.JPG	t
30	IMG_3532.JPG	upload_images/IMG_3532.JPG	t
31	IMG_3593.JPG	upload_images/IMG_3593.JPG	t
32	IMG_3594.JPG	upload_images/IMG_3594.JPG	t
33	IMG_3595.JPG	upload_images/IMG_3595.JPG	t
34	IMG_3596.JPG	upload_images/IMG_3596.JPG	t
35	IMG_3597.JPG	upload_images/IMG_3597.JPG	t
36	IMG_3665.JPG	upload_images/IMG_3665.JPG	t
37	IMG_3667.JPG	upload_images/IMG_3667.JPG	t
38	IMG_3666.JPG	upload_images/IMG_3666.JPG	t
39	IMG_3734.JPG	upload_images/IMG_3734.JPG	t
40	IMG_3735.JPG	upload_images/IMG_3735.JPG	t
41	IMG_3736.JPG	upload_images/IMG_3736.JPG	t
42	IMG_3810.JPG	upload_images/IMG_3810.JPG	t
43	IMG_3863.JPG	upload_images/IMG_3863.JPG	t
44	IMG_3936.JPG	upload_images/IMG_3936.JPG	t
60	20250313_174009_Page 1	upload_images/20250313_174009_page_1.jpg	t
62	20250313_174118_Page 1	upload_images/20250313_174118_page_1.jpg	t
64	20250313_174240_Page 1	upload_images/20250313_174240_page_1.jpg	t
65	IMG_3997.JPG	upload_images/IMG_3997.JPG	t
66	IMG_4124.JPG	upload_images/IMG_4124.JPG	t
67	IMG_4128.JPG	upload_images/IMG_4128.JPG	t
68	IMG_4129.JPG	upload_images/IMG_4129.JPG	t
69	IMG_4130.JPG	upload_images/IMG_4130.JPG	t
70	IMG_4161.JPG	upload_images/IMG_4161.JPG	t
71	IMG_4160.JPG	upload_images/IMG_4160.JPG	t
72	IMG_4163.JPG	upload_images/IMG_4163.JPG	t
73	IMG_4162.JPG	upload_images/IMG_4162.JPG	t
74	IMG_4164.JPG	upload_images/IMG_4164.JPG	t
75	IMG_4165.JPG	upload_images/IMG_4165.JPG	t
78	20250417_114751_Page 1	upload_images/20250417_114751_page_1.jpg	t
80	20250417_114829_Page 1	upload_images/20250417_114829_page_1.jpg	t
82	20250421_100728_Page 1	upload_images/20250421_100728_page_1.jpg	t
83	20250421_100753_Page 1	upload_images/20250421_100753_page_1.jpg	t
86	20250502_102237_Page 1	upload_images/20250502_102237_page_1.jpg	t
87	20250507_110702_Page 1	upload_images/20250507_110702_page_1.jpg	t
88	20250507_110709_Page 1	upload_images/20250507_110709_page_1.jpg	t
91	20250515_122538_Page 1	upload_images/20250515_122538_page_1.jpg	t
92	20250515_122548_Page 1	upload_images/20250515_122548_page_1.jpg	t
93	20250526_161159_Page 1	upload_images/20250526_161159_page_1.jpg	t
94	20250526_161205_Page 1	upload_images/20250526_161205_page_1.jpg	t
95	20250602_001708_Page 1	upload_images/20250602_001708_page_1.jpg	t
96	20250602_001710_Page 2	upload_images/20250602_001710_page_2.jpg	t
97	20250611_081024_Page 1	upload_images/20250611_081024_page_1.jpg	t
98	20250611_081025_Page 2	upload_images/20250611_081025_page_2.jpg	t
99	20250611_081026_Page 3	upload_images/20250611_081026_page_3.jpg	t
100	20250617_053151_Page 1	upload_images/20250617_053151_page_1.jpg	t
101	20250617_053843_Page 1	upload_images/20250617_053843_page_1.jpg	t
102	20250617_053845_Page 2	upload_images/20250617_053845_page_2.jpg	t
103	20250617_053845_Page 3	upload_images/20250617_053845_page_3.jpg	t
104	20250630_034103_Page 1	upload_images/20250630_034103_page_1.jpg	t
105	20250704_085136_Page 1	upload_images/20250704_085136_page_1.jpg	t
106	20250704_085137_Page 2	upload_images/20250704_085137_page_2.jpg	t
107	20250704_085138_Page 3	upload_images/20250704_085138_page_3.jpg	t
108	20250704_085138_Page 4	upload_images/20250704_085138_page_4.jpg	t
109	20250704_085139_Page 5	upload_images/20250704_085139_page_5.jpg	t
110	20250708_003421_Page 1	upload_images/20250708_003421_page_1.jpg	t
112	20250708_020615_Page 1	upload_images/20250708_020615_page_1.jpg	t
113	20250715_075603_Page 1	upload_images/20250715_075603_page_1.jpg	t
114	20250715_075604_Page 2	upload_images/20250715_075604_page_2.jpg	t
115	20250728_001807_Page 1	upload_images/20250728_001807_page_1.jpg	t
116	20250728_001809_Page 2	upload_images/20250728_001809_page_2.jpg	t
117	20250728_001810_Page 3	upload_images/20250728_001810_page_3.jpg	t
118	20250728_001811_Page 4	upload_images/20250728_001811_page_4.jpg	t
119	20250804_035116_Page 1	upload_images/20250804_035116_page_1.jpg	t
120	20250804_035116_Page 1	upload_images/20250804_035116_page_1_GAv2ag6.jpg	t
121	20250812_073455_Page 1	upload_images/20250812_073455_page_1.jpg	t
122	20250812_073513_Page 1	upload_images/20250812_073513_page_1.jpg	t
123	20250818_092834_Page 1	upload_images/20250818_092834_page_1.jpg	t
124	20250818_092837_Page 1	upload_images/20250818_092837_page_1.jpg	t
125	20250821_233057_Page 1	upload_images/20250821_233057_page_1.jpg	t
126	20250821_233058_Page 2	upload_images/20250821_233058_page_2.jpg	t
128	20250821_233110_Page 1	upload_images/20250821_233110_page_1.jpg	t
130	20250825_003736_Page 1	upload_images/20250825_003736_page_1.jpg	t
132	20250825_003737_Page 2	upload_images/20250825_003737_page_2.jpg	t
140	IMG_6132.JPG	upload_images/IMG_6132.JPG	t
133	20250914_044945_Page 1	upload_images/20250914_044945_page_1.jpg	t
134	20250914_044946_Page 1	upload_images/20250914_044946_page_1.jpg	t
137	20250922_081209_Page 1	upload_images/20250922_081209_page_1.jpg	t
138	20250922_081210_Page 2	upload_images/20250922_081210_page_2.jpg	t
139	20250922_081211_Page 3	upload_images/20250922_081211_page_3.jpg	t
141	20250929_062204_Page 1	upload_images/20250929_062204_page_1.jpg	t
164	20251216_001143_Page 1	upload_images/20251216_001143_page_1.jpg	t
154	20251119_004026_Page 1	upload_images/20251119_004026_page_1.jpg	t
142	20251006_083417_Page 1	upload_images/20251006_083417_page_1.jpg	t
165	20251216_001143_Page 2	upload_images/20251216_001143_page_2.jpg	t
143	20251006_083417_Page 2	upload_images/20251006_083417_page_2.jpg	t
144	20251006_083418_Page 3	upload_images/20251006_083418_page_3.jpg	t
145	20251015_040852_Page 1	upload_images/20251015_040852_page_1.jpg	t
146	20251015_040852_Page 2	upload_images/20251015_040852_page_2.jpg	t
147	20251021_001159_Page 1	upload_images/20251021_001159_page_1.jpg	t
148	20251021_001313_Page 1	upload_images/20251021_001313_page_1.jpg	t
155	20251125_050230_Page 1	upload_images/20251125_050230_page_1.jpg	t
156	20251125_050230_Page 2	upload_images/20251125_050230_page_2.jpg	t
149	20251105_033028_Page 1	upload_images/20251105_033028_page_1.jpg	t
150	20251105_033028_Page 2	upload_images/20251105_033028_page_2.jpg	t
153	20251118_054630_Page 2	upload_images/20251118_054630_page_2.jpg	t
151	20251114_000719_Page 1	upload_images/20251114_000719_page_1.jpg	t
157	20251125_050230_Page 3	upload_images/20251125_050230_page_3.jpg	t
152	20251118_054630_Page 1	upload_images/20251118_054630_page_1.jpg	t
166	20251219_055658_Page 1	upload_images/20251219_055658_page_1.jpg	t
158	20251201_001359_Page 1	upload_images/20251201_001359_page_1.jpg	t
159	20251201_001400_Page 2	upload_images/20251201_001400_page_2.jpg	t
160	20251203_083155_Page 1	upload_images/20251203_083155_page_1.jpg	t
161	20251203_083155_Page 2	upload_images/20251203_083155_page_2.jpg	t
163	20251208_060451_Page 1	upload_images/20251208_060451_page_1.jpg	t
167	20251222_052438_Page 1	upload_images/20251222_052438_page_1.jpg	t
168	20251222_052438_Page 2	upload_images/20251222_052438_page_2.jpg	t
169	20251222_052438_Page 3	upload_images/20251222_052438_page_3.jpg	t
\.


--
-- Data for Name: receipts_receipt; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public.receipts_receipt (id, "日付", "価格", "登録番号", "備考", "項目コード_id", "PDF番号_id") FROM stdin;
6	2024-09-14	7150	0		005	1
7	2024-09-14	1090	1010001112577		001	1
8	2024-09-07	750	1010001112577		001	1
9	2024-08-31	2390	9010701005544		001	2
10	2024-08-31	6380	5013201003484		001	2
11	2024-08-12	7084	9020001109227		001	2
12	2024-09-09	700	3010701025003		001	3
13	2024-09-08	5640	0		001	3
14	2024-09-05	1600	3010002023350		002	4
15	2024-09-07	2640	0		002	4
16	2024-09-11	656	7180301016951		001	5
17	2024-09-02	560	3010701025003		001	5
18	2024-09-06	560	3010701025003		001	6
19	2024-09-05	140	1010001112577		001	6
20	2024-09-04	560	3010701025003		001	7
21	2024-09-19	2350	1011001073818	みっちゃん　佐藤さんと昼食	001	9
22	2024-09-21	3405	4010001107120	ENEOS	001	10
23	2024-09-21	2190	9010701005544	KFC	001	10
24	2024-09-21	5819	9010401054189	COCOS	001	10
25	2024-09-25	2830	0	今井医院	001	11
26	2024-09-25	1090	0	アイン薬局	001	11
27	2024-10-07	2420	4120001068905	Book 1st	001	12
28	2024-09-28	6400	4011001123768	Anchor Point	001	12
29	2024-10-05	6600	4810210395012	QING	001	13
30	2024-10-08	19810	2011001127829	TOKYU	001	13
31	2024-10-15	1180	0	新倉歯科	001	14
32	2024-10-12	6160	3011001120832	Gourmand	001	14
33	2024-10-27	10760	8010901026085	いしはら	002	15
34	2024-10-26	5280	6010901033950	ゴルアンブル	002	15
35	2024-11-02	2640	4810210395012	Qing	001	15
36	2024-11-01	2190	9010701005544	KFC	002	16
37	2024-10-19	5940	3010401011708	しゃぶせん	002	16
38	2024-11-03	2798	4010001107120	ENEOS	004	16
39	2024-10-20	3850	5011001043791	GOOD CHEESE	002	17
40	2024-11-03	1980	2040001074194	KAMOGAWA BAKERY	002	17
41	2024-11-10	4730	3011001148808	洋食ムチユ	001	18
42	2024-11-09	4760173	1120001087528	GM Cafe	001	18
43	2024-11-16	5302	7013201012145	Hacienda	002	19
44	2024-11-15	2700	1010401029669	Core Kitchen	002	19
45	2024-11-17	3663	3010701029400	くらた	002	19
46	2024-11-12	4000	5011001120987	OAK	002	19
47	2024-11-18	200	0	印鑑証明	005	20
48	2024-11-30	440	5013301012443	ラクーア文房具	001	20
49	2024-12-01	3873	3013202002074	キャトル	002	20
50	2024-12-04	700	3010701025003		001	21
51	2024-12-23	8800	9810392065799	やまもと	002	21
52	2024-11-23	5150	3070001004866	研究費	002	22
53	2024-11-28	10257	1010601002789	すしざんまい	002	22
54	2024-11-23	2763	4010001107120	ENEOS	004	22
55	2024-12-25	12500	501090105355	月亭	002	23
56	2024-12-08	22660	2010701022983	Black Terrace	002	24
58	2024-12-15	5200	0	VillaSeiya	002	24
59	2024-12-30	1275	1011202005859	セブン年賀状	001	25
60	2024-12-02	1000	0	東急	001	25
61	2025-01-01	900	9040001037376		003	25
62	2024-12-23	1210	5011001027621	LOFT書籍	001	26
63	2025-01-02	1633	5013301008549	TOBU	002	26
64	2024-12-02	900	5013301008549	TOBU	002	26
65	2024-12-28	2800	2011801029712	浅利食堂	002	27
66	2025-01-28	1274	1010401088137	Sebastian	001	27
67	2025-01-03	18865	5013301044453	Buta Ball	001	28
68	2024-12-30	4698	0	Taj Mahal	001	28
69	2025-01-04	1301	5180001037119	Sugimoto	001	28
70	2025-01-03	1000	4010001098525	Ohagi	001	29
71	2025-01-03	5100	8010702009850	Cucchina	001	29
72	2024-12-21	3025	3180001017964		001	30
73	2024-12-21	22000	7010701002766		001	30
74	2024-12-29	4675	9100001008924		001	30
81	2025-01-19	6600	5120001077467	高島屋	002	32
82	2025-01-12	280	5013301012443	Muji Cafe	002	31
83	2025-01-12	280	5013301012443	Muji Cafe	002	31
84	2025-01-12	280	5013301012443	Muji Cafe	002	31
85	2025-01-12	580	5013301012443	Muji Cafe	002	31
86	2025-01-08	1210	4290001000470	宮下公園打ち合わせ	001	33
88	2025-01-11	5000	6010401152730	アロッサマヌエル	002	33
89	2025-01-08	756	5011001027621	LOFT	001	34
90	2025-01-12	3802	2012401030556	バーミヤン	001	34
91	2025-01-12	4090	3070001004866	ベイシア	001	34
92	2025-01-12	2891	4010001107120	ENEOS	004	35
93	2025-01-06	2200	9010001134416	Maruzen書籍	005	35
94	2025-01-08	1870	5013201001604	恭文堂	001	35
95	2025-01-26	9240	4810786833410	cucchiaio	003	36
96	2025-01-26	1000	0	Tokyu	004	36
97	2025-02-03	820	2010001013659	海洋文具新橋	001	36
98	2025-01-31	1160	0	AIN	001	37
99	2025-01-25	2240	9010701005544	KFC	002	37
100	2025-02-02	4433	5040002070685	Enejet	004	38
101	2025-02-02	2015	1040001073882	Nakapan	002	38
102	2025-02-02	34865	7010401145659	Gokuu	003	38
103	2025-02-24	2719	5040002070685	Enejet	001	39
104	2025-02-23	5260	4810956153458	いせや	001	39
105	2025-02-11	1242	3130001012441	王将	001	39
106	2025-01-29	3604	5011001027621	ロフト	001	39
107	2025-02-23	18158	3070001006474	CAINZ	001	40
108	2025-02-23	2222	3070001004866	BEISIA	001	40
109	2025-02-22	4210	4010001148370	スシロー	002	41
110	2025-02-01	1960	0	SEAFOOD COURT	002	41
111	2025-02-15	4010	3430001044958	ニトリ	001	42
112	2025-02-15	1954	1430001010672	ツルハドラッグ	001	42
113	2025-02-16	3300	1020001068083	ワークランド	001	42
114	2025-02-15	8046	6010701008509	バタフライビー	001	42
115	2025-03-04	31845	8010001220670	Ys ROAD	001	43
116	2025-03-01	5148	9010401054189	COCOs	001	43
117	2025-03-02	2543	5040002070685	ENEOS	001	43
118	2025-03-10	490	1010001112577	POST OFFICE	001	44
119	2025-03-08	1350	7810131888264	Parlor Okumura	002	44
120	2025-03-08	3750	7810131888264	Parlor Okumura	002	44
121	2025-03-17	16610	8010001220670	Ys Road	001	65
122	2025-03-11	924	9010001134416	Maruzen	005	65
123	2025-03-19	29800	3011103003992	Apple	001	60
124	2025-03-13	179800	3011103003992	Apple	001	62
125	2025-03-19	1800	3011103003992	Apple	001	64
126	2025-03-14	13200	1011001028441	ARROWS	001	66
127	2025-03-15	2970	3011001148808	Muchu	001	66
128	2025-03-15	1320	1430001010672	Tsuruha	001	66
129	2025-03-22	2250	0	Iname	002	67
130	2025-03-22	4100	0	Iname	002	68
131	2025-03-23	2834	5040002070685	Eneos	001	69
132	2025-03-22	7110	3070001004866	Beisia	001	69
133	2025-03-22	898	3070001006474	Cains	001	69
134	2025-03-29	31218	2011101088599	SEIYO GINZA	001	70
135	2025-03-27	2240	9010701005544	KFC	001	70
136	2025-02-28	43340	1011001028441	ARROWS	001	70
137	2025-03-14	12200	1011001028441	Green Label	001	71
138	2025-03-27	1100	7013201005553	Matterhorn	001	71
139	2025-02-07	4880	0	健康診断	005	72
140	2025-02-07	4370	0	健康診断	005	74
141	2025-02-08	1300	5013301012443	MUJI	001	73
142	2025-02-08	1300	5013301012443	MUJI	001	73
143	2025-02-08	1300	5013301012443	MUJI	001	73
144	2025-02-09	2914	5040002070685	ENEJET	004	73
145	2025-03-31	220	0	税金更正	005	75
146	2025-04-15	1402	6010401000518	ICS TEL	001	80
147	2025-04-03	15750	2011001127829	TOKYU	003	78
148	2025-04-03	250	1010001112577	POST	005	78
149	2025-04-05	6400	6010001158442	OPUS	003	78
150	2025-04-19	1450	0	Imai	005	83
151	2025-04-19	1160	0	薬	005	82
152	2025-04-20	4500	5070001038623	MicoMico	002	82
153	2025-04-20	1650	4011101005131	Kinokuniya Books	005	82
154	2025-04-19	4600	1101100103735	Ceder the chop	002	86
155	2025-04-20	4000	5013301012443	無印	001	86
156	2025-04-26	2418	0	The Bakery	002	86
157	2025-01-09	5000	0	東急電鉄	004	86
158	2025-05-04	2841	504000207685	Enejet	004	87
159	2025-05-03	5340	4810956153458	ISEYA	002	87
160	2025-05-03	5708	3070001004866	BEISIA	001	87
161	2025-05-05	3300	4810210395012	Qing	002	87
162	2025-05-04	3000	5040002070685	ENEJET	001	88
163	2025-05-04	5359	5040002070685	ENEJET	001	88
164	2025-05-13	680	5010701019713	MOS	001	92
165	2025-05-13	1848	3011001096370	Donkihote	001	92
166	2025-05-13	1800	7011801004280	Taxi	001	92
167	2025-05-13	700	7012401015908	Taxi	001	92
168	2025-05-13	1600	8010801018901	Taxi	001	92
169	2025-05-11	2000	1250001002853	GU	001	91
170	2025-05-11	1990	9250001001451	Uniqlo	001	91
171	2025-05-13	11880	7010001040434	Kandagawa	002	91
172	2025-05-24	3025	6010901012855	箸庵	002	93
173	2025-05-18	5738	2011001104448	EATERY	002	93
174	2025-05-25	6000	3011101060879	夏目亭	002	93
175	2025-05-24	2340	9180001036703	HARBS	002	94
176	2025-05-24	430	1010001112577	郵便局	005	94
177	2025-05-15	900	1011301020296	Taxi	003	94
178	2025-05-30	1980	3810397073670	ネームプレートパワー新橋	005	96
179	2025-06-01	3560	7011001093100	星火	002	96
180	2025-05-31	4356	6011001055489	Public House	002	95
181	2025-06-01	1985	4011101045656	Bleu Bleuet	001	95
182	2025-06-08	3900	9010701029923	BeBe 目黒	002	98
183	2025-06-06	6908	5260001007212	イオンリカー	005	98
184	2025-06-07	4100	1020001129686	Pizza Hut	002	98
185	2025-05-19	93500	6120001245312	タナベコンサルティング	005	97
186	2025-06-07	2120	3013202002074	Cattle	002	99
187	2025-06-10	6700	3810599148270	たちばな	003	99
188	2025-06-12	1600	2011701001317	S.RIDE	004	100
189	2025-06-12	16610	2290001013573	赤坂うまや	003	100
190	2025-06-13	1000	5010601042047	日の丸	004	100
191	2025-06-15	2447	1430001010672	つるは	005	100
192	2025-06-12	1000	9011101048118	Tallis	002	101
193	2025-06-13	1140	8011191083968	Bingo	001	101
194	2025-06-12	1400	1010601027134	帝都自動車	003	101
195	2025-06-13	2400	2010801002719	S.Ride	004	101
196	2025-05-16	800	1010001112577	収入印紙	005	101
197	2025-06-12	4180	8010001196358	SHARI GINZA	003	102
198	2025-06-12	900	7010901032448	kmグループ	004	102
199	2025-06-12	1300	6100601013466	株式会社 Z	004	102
200	2025-06-12	2000	1810481951940	TATE TAXI	004	102
201	2025-06-13	170610	4010002044008	GCC	003	103
202	2025-06-13	1600	2011401006509	S.Ride	004	103
203	2025-06-30	194260	7020001070117	不二サッシ	005	104
204	2025-07-02	123900	1010801005930	鈴美商事	005	105
205	2025-07-01	1450	0	今井医院	005	106
206	2025-06-06	6908	5260001007212	イオンリカー	005	107
207	2025-07-02	1160	0	アイン薬局	005	107
208	2025-06-21	7466	3070001004866	Beisia	001	108
209	2025-06-21	3580	4810958153458	いせや	002	108
210	2025-06-29	3190	8010901026085	いしはら	002	109
211	2025-06-17	3600	0	ひさご	002	109
212	2025-06-24	110	1010001112577	郵便局	005	110
213	2025-07-06	2695	8011001020730	RITUEL	002	110
214	2025-06-28	9314	8010401045627	Le Pristine Cafe	002	112
215	2025-07-05	4100	1020001129686	Pizza Hut	002	112
216	2025-07-12	5350	2011001127829	TOKYU	003	113
217	2025-07-12	2190	9010901029756	CoCoIchi	001	113
218	2025-07-09	4400	4011101006006	KEIO	001	114
219	2025-07-11	2190	9010701005544	KFC	001	114
220	2025-07-19	3170	5010401185789	Conico/Colmena	001	115
221	2025-07-13	3100	3011101065003	Garden	001	115
222	2025-07-26	4503	5040002070685	Enejet	004	116
223	2025-07-21	1990	1250001002853	GU	001	116
224	2025-07-21	3990	9250001001451	Uniqlo	001	116
225	2025-07-26	1500	8010001140514	Mitsui Repark	004	117
226	2025-07-26	300	8010001140514	Mitsui Repark	004	117
227	2025-07-25	1800	8010001140514	Mitsui Repark	004	117
228	2025-07-18	4000	8010801021582	四川餃子房	002	118
229	2025-07-21	2050	3013201013691	立野屋	002	118
230	2025-08-02	1971	7180301016951	Sugi Yakkyoku	001	119
231	2025-08-02	1100	8010801018901	Taxi Kokusai Kogyo	004	119
232	2025-08-02	1000	8011501002658	Dainihon Kotsu	004	119
233	2025-08-02	1000	7010601045948	Daiwa Jidosha	004	119
234	2025-08-03	7600	4810210395012	Qing	002	120
235	2025-08-02	6652	4011001168920	ShinQs	002	120
236	2025-08-07	935	2013201000063	アーンズ	001	121
237	2025-08-08	1100	7010901032448	国際自動車	004	121
238	2025-08-08	1400	6810612576892	小松タクシー	004	121
239	2025-08-09	0	7011101011044	世界堂	001	122
240	2025-07-28	1200	8010001140514	三井リパーク	004	122
241	2025-08-18	2900	3810397073670	バワー新橋	001	123
242	2025-08-18	5600	8810674487167	尚半	002	123
243	2025-08-18	4917	2020001082959	TINY NATURA MARKET	002	123
244	2025-08-16	5460	2040001000456	AOEN STYLE	001	124
245	2025-08-17	1990	9250001001451	UNIQLO	001	124
246	2025-08-17	3000	1250001002853	GU	001	124
247	2025-08-21	3740	2011101035312	ACCEA	005	125
248	2025-08-20	2123	2011101035312	ACCEA	005	125
249	2025-08-19	2123	2011101035312	ACCEA	005	125
250	2025-08-21	9240	2011101035312	ACCEA	005	125
251	2025-08-20	900	7030001093694	織田タクシー	004	126
252	2025-08-20	1900	4010901010019	ビゲスト	004	126
253	2025-08-20	900	9011801023650	東京タクシー	004	126
254	2025-08-20	1000	5011601002271	国産自動車交通	004	126
255	2025-08-19	150	2010001013659	海洋文具	001	128
256	2025-08-16	6709	5011001043791	TWELVE ON THE PARK	002	128
257	2025-08-19	410	7180301016951	すぎ薬局	001	128
258	2025-08-23	4100	8120001062235	Cafe Cardinal	002	132
259	2025-08-22	1000	5010702003591	佐藤靴鞄修理	001	132
260	2025-08-23	1800	8120001062235	Cafe Cardinal	002	130
261	2025-08-23	7600	8120001062235	Cafe Cardinal	002	130
262	2025-09-28	3091	1100001038458	CITY BAKERY	002	140
263	2025-09-28	462	1100001038458	CITY BAKERY	002	140
264	2025-08-30	6940	9010401128868	TRUNK HOTEL	002	133
265	2025-09-09	470	7011001031943	STARBUCKS	001	134
266	2025-09-01	12980	9013301010402	Biccamera	001	134
267	2025-09-14	2973	5040002070685	ENEOS	004	137
268	2025-09-17	600	1010001112577	POST OFFICE	001	137
269	2025-09-15	3400	2011001058404	Taste and Sense	001	137
270	2025-09-18	280	7011202010564	DOTOUR	001	138
271	2025-09-21	1000	1011202005859	\N	005	138
272	2025-09-20	3750	8010702009850	TOSCANA	002	138
273	2025-09-21	4697	3011001137967	L Aterlier de Stand Banh Mi	002	139
274	2025-09-07	4200	9010401089202	Bricolage	002	141
275	2025-09-07	4811	8010401017312	たぬき煎茶	002	141
276	2025-09-07	2375	8010701011279	九州屋	004	141
277	2025-10-04	1500	5013301012443	MUJI	002	142
278	2025-10-04	1500	5013301012443	MUJI	002	142
279	2025-10-04	7756	3070001004866	Beisia	005	142
280	2025-10-05	2581	5040002070685	Eneos	004	142
281	2025-09-06	3240	4040001093457	Shirakutei	001	143
282	2025-09-28	462	0	GRANDTREE	001	143
283	2025-09-28	3091	0	GRANDTREE	001	143
285	2025-10-03	1590	0	Yukikata	005	144
286	2025-09-06	2800	0	Shiraku	002	144
287	2025-10-12	2587	5040002070685	Enejet	004	145
288	2025-10-11	8000	5040001074258	Kamogawakan	001	145
289	2025-10-11	2701	3070001004866	Beisia	001	145
290	2025-10-13	777	1430001010672	Tsuruha	001	146
291	2025-10-10	1105	1010001112577	Post Office	001	146
292	2025-10-07	1900	3810397073670	Power	001	146
293	2025-10-16	13850	9011001029597	JR	004	147
294	2025-10-16	13850	9011001029597	JR	004	147
295	2025-10-17	13037	5011001095180	TORIFITO	001	148
296	2025-11-02	7000	1010401009712	華都飯店	002	149
297	2025-11-04	1000	4010601016266	TAXI	004	149
298	2025-11-05	110	1010001112577	JPOST	005	150
299	2025-11-05	862	718030106951	Sugi	001	150
300	2025-10-25	630	0	Ain Drugs	001	151
301	2025-10-09	1470	0	Yukikata	001	151
302	2025-11-10	430	1010001112577	POST	001	151
303	2025-11-16	2570	5040002070685	ENEJET	004	152
304	2025-11-15	3135	9010401054189	COCOS	002	152
305	2025-11-16	470	7011001031943	Starbucks	002	152
306	2025-11-11	26	1010001112577	POST	005	153
307	2025-11-15	9375	3070001004866	BEISIA	001	153
308	2025-11-18	280	7011202010564	Dotor	001	154
309	2025-11-18	280	7011202010564	Dotor	001	154
310	2025-11-17	749	0	AMAZON	001	155
311	2025-11-21	200	0	証明書	005	155
312	2025-11-22	591	3070001004866	BEISIA	004	156
313	2025-11-21	300	0	戸籍化	005	156
315	2025-11-22	6600	4810956153458	Iseya	002	157
316	2025-11-24	2013	6010401005715	La Bohemu	005	157
317	2025-11-21	1000	0	Bario	002	157
318	2025-11-29	2844	5040002070685	Enejet	004	158
319	2025-11-29	495	3070001004866	BEISIA	001	158
320	2025-11-29	2274	3070001006474	CAINZ	001	158
321	2025-11-29	2140	0	Tabito	002	159
322	2025-11-29	2470	4010001148370	Sushiro	001	159
323	2025-12-02	1499	8010401045627	Pastry Shop	002	160
324	2025-10-23	1600	2010801006457	Taiyo Motors	001	160
325	2025-12-03	2673	5120105004895	PL Tokyo Kenko	001	161
326	2025-12-04	36915	9010001026704	Ester	001	163
327	2025-12-06	6000	2011001098211	Minebal	001	163
328	2025-12-15	3200	7010401013097	新生堂	003	164
329	2025-12-13	4169	3070001004866	Beisia	001	164
330	2025-12-15	660	6011001032554	Dotour	001	164
331	2025-12-14	2644	5040002070685	ENEOS	004	165
332	2025-12-13	1500	5013301012443	MUJI	001	165
333	2025-12-13	1500	5013301012443	MUJI	001	165
334	2025-12-13	7090	4810956153458	Iseya	001	165
335	2025-12-16	430	1010001112577	JPOST	001	166
336	2025-12-18	1160	9080001003300	Tamiya	001	166
337	2025-12-20	1590	0	調剤薬局	001	167
338	2025-10-28	1500	0	調剤薬局	001	167
339	2025-12-18	1630	7010401013097	新正堂	003	168
340	2025-09-25	2100	0	Yukikata	001	168
341	2025-12-20	5800	3011001040717	Appetito	002	169
342	2025-09-05	1160	0	調剤薬局	005	169
\.


--
-- Data for Name: receipts_項目リスト; Type: TABLE DATA; Schema: public; Owner: konno
--

COPY public."receipts_項目リスト" ("項目コード", "項目印字名", "項目短縮名", "項目レポート分類区分") FROM stdin;
001	消耗品	消毛	001
002	会議費	会議	002
003	接待交際費	交際	003
004	旅費交通費	旅通	004
005	その他	他	005
\.


--
-- Name: account_emailaddress_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.account_emailaddress_id_seq', 1, false);


--
-- Name: account_emailconfirmation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.account_emailconfirmation_id_seq', 1, false);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 44, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 1, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 11, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 36, true);


--
-- Name: receipts_pdf番号_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public."receipts_pdf番号_id_seq"', 169, true);


--
-- Name: receipts_receipt_id_seq; Type: SEQUENCE SET; Schema: public; Owner: konno
--

SELECT pg_catalog.setval('public.receipts_receipt_id_seq', 342, true);


--
-- Name: account_emailaddress account_emailaddress_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_pkey PRIMARY KEY (id);


--
-- Name: account_emailaddress account_emailaddress_user_id_email_987c8728_uniq; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_email_987c8728_uniq UNIQUE (user_id, email);


--
-- Name: account_emailconfirmation account_emailconfirmation_key_key; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_key_key UNIQUE (key);


--
-- Name: account_emailconfirmation account_emailconfirmation_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirmation_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: receipts_pdf番号 receipts_pdf番号_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public."receipts_pdf番号"
    ADD CONSTRAINT "receipts_pdf番号_pkey" PRIMARY KEY (id);


--
-- Name: receipts_receipt receipts_receipt_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.receipts_receipt
    ADD CONSTRAINT receipts_receipt_pkey PRIMARY KEY (id);


--
-- Name: receipts_項目リスト receipts_項目リスト_pkey; Type: CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public."receipts_項目リスト"
    ADD CONSTRAINT "receipts_項目リスト_pkey" PRIMARY KEY ("項目コード");


--
-- Name: account_emailaddress_email_03be32b2; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX account_emailaddress_email_03be32b2 ON public.account_emailaddress USING btree (email);


--
-- Name: account_emailaddress_email_03be32b2_like; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX account_emailaddress_email_03be32b2_like ON public.account_emailaddress USING btree (email varchar_pattern_ops);


--
-- Name: account_emailaddress_user_id_2c513194; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX account_emailaddress_user_id_2c513194 ON public.account_emailaddress USING btree (user_id);


--
-- Name: account_emailconfirmation_email_address_id_5b7f8c58; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX account_emailconfirmation_email_address_id_5b7f8c58 ON public.account_emailconfirmation USING btree (email_address_id);


--
-- Name: account_emailconfirmation_key_f43612bd_like; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX account_emailconfirmation_key_f43612bd_like ON public.account_emailconfirmation USING btree (key varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: receipts_receipt_PDF番号_id_f438910d; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX "receipts_receipt_PDF番号_id_f438910d" ON public.receipts_receipt USING btree ("PDF番号_id");


--
-- Name: receipts_receipt_項目コード_id_a0799e58; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX "receipts_receipt_項目コード_id_a0799e58" ON public.receipts_receipt USING btree ("項目コード_id");


--
-- Name: receipts_receipt_項目コード_id_a0799e58_like; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX "receipts_receipt_項目コード_id_a0799e58_like" ON public.receipts_receipt USING btree ("項目コード_id" varchar_pattern_ops);


--
-- Name: receipts_項目リスト_項目コード_0d4b4159_like; Type: INDEX; Schema: public; Owner: konno
--

CREATE INDEX "receipts_項目リスト_項目コード_0d4b4159_like" ON public."receipts_項目リスト" USING btree ("項目コード" varchar_pattern_ops);


--
-- Name: unique_primary_email; Type: INDEX; Schema: public; Owner: konno
--

CREATE UNIQUE INDEX unique_primary_email ON public.account_emailaddress USING btree (user_id, "primary") WHERE "primary";


--
-- Name: unique_verified_email; Type: INDEX; Schema: public; Owner: konno
--

CREATE UNIQUE INDEX unique_verified_email ON public.account_emailaddress USING btree (email) WHERE verified;


--
-- Name: account_emailaddress account_emailaddress_user_id_2c513194_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.account_emailaddress
    ADD CONSTRAINT account_emailaddress_user_id_2c513194_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: account_emailconfirmation account_emailconfirm_email_address_id_5b7f8c58_fk_account_e; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.account_emailconfirmation
    ADD CONSTRAINT account_emailconfirm_email_address_id_5b7f8c58_fk_account_e FOREIGN KEY (email_address_id) REFERENCES public.account_emailaddress(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: receipts_receipt receipts_receipt_PDF番号_id_f438910d_fk_receipts_pdf番号_id; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.receipts_receipt
    ADD CONSTRAINT "receipts_receipt_PDF番号_id_f438910d_fk_receipts_pdf番号_id" FOREIGN KEY ("PDF番号_id") REFERENCES public."receipts_pdf番号"(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: receipts_receipt receipts_receipt_項目コード_id_a0799e58_fk_receipts_項目; Type: FK CONSTRAINT; Schema: public; Owner: konno
--

ALTER TABLE ONLY public.receipts_receipt
    ADD CONSTRAINT "receipts_receipt_項目コード_id_a0799e58_fk_receipts_項目" FOREIGN KEY ("項目コード_id") REFERENCES public."receipts_項目リスト"("項目コード") DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict PGyhjz8Kz5ObgT8DGHsgFeH0tyZ16jZBmEHLYUFAXRZ1RrZcHJH9Sni4lc12vlq

--
-- PostgreSQL database cluster dump complete
--

