# Generated by Django 5.0.7 on 2024-08-30 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='項目リスト',
            fields=[
                ('項目コード', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('項目印字名', models.CharField(max_length=100)),
                ('項目短縮名', models.CharField(blank=True, max_length=50)),
                ('項目レポート分類区分', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('日付', models.DateField()),
                ('価格', models.PositiveIntegerField()),
                ('登録番号', models.IntegerField()),
                ('備考', models.CharField(blank=True, max_length=255, null=True)),
                ('項目コード', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receipts.項目リスト')),
            ],
        ),
    ]
