# Generated by Django 5.0.7 on 2024-08-31 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='PDF番号',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
