# Generated by Django 5.0.7 on 2024-08-31 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_receipt_pdf番号'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDF番号',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PDF番号', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='receipt',
            name='PDF番号',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts_by_pdf_number', to='receipts.項目リスト'),
        ),
    ]
