# Generated by Django 5.0.7 on 2024-09-01 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0003_pdf番号_alter_receipt_pdf番号'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf番号',
            name='upload',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
