# Generated by Django 5.0.7 on 2024-09-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0004_pdf番号_upload'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf番号',
            old_name='PDF番号',
            new_name='PDF_num',
        ),
        migrations.AlterField(
            model_name='pdf番号',
            name='upload',
            field=models.ImageField(upload_to='..\\..\\media\\upload_images'),
        ),
    ]
