# Generated by Django 5.0.7 on 2024-09-02 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0005_rename_pdf番号_pdf番号_pdf_num_alter_pdf番号_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf番号',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pdf番号',
            name='upload',
            field=models.ImageField(upload_to='upload_images/'),
        ),
    ]
