# Generated by Django 5.0.7 on 2024-09-04 01:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_pdf番号_processed_alter_pdf番号_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='PDF番号',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts_by_pdf_number', to='receipts.pdf番号'),
        ),
    ]
