# Generated by Django 5.1.2 on 2025-01-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_receipt_pdf番号'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='価格',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='登録番号',
            field=models.IntegerField(default=0),
        ),
    ]
