# Generated by Django 5.1.2 on 2025-09-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0008_alter_receipt_価格_alter_receipt_登録番号'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='登録番号',
            field=models.BigIntegerField(default=0),
        ),
    ]
